apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: fiap-cloud-games
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: maicaoxd/fiap-cloud-games-users-api:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: users-api-configmap
            - secretRef:
                name: users-api-secret
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
