apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  namespace: fiap-cloud-games
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Server=users-sqlserver,1433;Database=FiapCloudGamesUsers;User Id=sa;Password=Fcg@123456;TrustServerCertificate=True;Encrypt=False
  Jwt__Secret: fiap-cloud-games-local-development-secret-key
  RabbitMq__Username: guest
  RabbitMq__Password: guest
